version: "3.9"

services:
  # Our Postgres database
  integrationdb: # The service will be named db.
    image: postgres # The postgres image will be used
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: dev # POSTGRES_USER env var w/ value rob
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb # Database name
    ports: # Expose ports so that apps not running via docker-compose can connect to them.
      - 5433:5432 # format here is "port on our machine":"port on container"
    networks:
      - integration_test_network
networks:
  integration_test_network:
    name: integration_test_network